# phases:
#   pre_build:
#     commands:
#       - echo Entered prebuild phase
#   build:
#     commands:
#       - echo Build started on `date`
#       - mvn clean package  
#   post_build:
#     commands:
#       - echo Build completed
# artifacts:
#   files:
#     - target/employee-0.0.1-SNAPSHOT.jar
#   discard-paths: yes


# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9

  pre_build:
    commands:
      - echo Entered prebuild phase on `date`
      
      - apt-get install -y python3-venv
      - python3.9 -m venv test_venv
      - ./test_venv/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest

  build:
    commands:
      - echo Build started on `date`
      - python -m unittest -v tests/test_*.py
#      working-directory: .
      
  post_build:
    commands:
      - echo Build completed on `date`
